version: '3'
services:
  postgres:
    image: postgres:13
    container_name: 'my-postgres'
    ports:
      - '5444:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=db'
  app:
    build: ./
    container_name: 'my-app'
    ports:
      - '8081:8080'
    environment:
      - 'DATASOURCE_INFO=192.168.0.105'